project:
  type: book
  output-dir: docs

book:
  title: |
    **Tutoriais Compras.gov.br**
    *para Conteúdo Local e Margem de Preferência*
  subtitle: Versão 0.2
  date: "2026-02-21"
  repo-url: https://github.com/gestaogovbr/contratacoes-tutoriais
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - conteudo_local.qmd
    - margem_de_preferencia.qmd

lang: pt-BR

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    number-sections: false
    link-external-newwindow: true
  pdf:
    documentclass: report
    fontsize: "11pt"
    papersize: a4
    geometry:
      - margin=1.5cm
    fig-pos: "H"
    fig-align: "center"
    colorlinks: true
    linkcolor: "blue"
    urlcolor: "red"
    citecolor: "green"
    header-includes:
      - \renewcommand{\familydefault}{\sfdefault}
